# version format
version: 2.0.1.{build}

# Do not build on tags
skip_tags: true


build_script:
  - cd Packaging
  - build.bat

artifacts:
  - path: Packaging\Packages\*.nupkg
  - path: Packaging\Packages\*.zip
 
 
#deploy:
#  provider: NuGet
#  server:
#  api_key:
#    secure: 
#  artifact: /.*\.nupkg/